# Generated by Django 4.0.2 on 2022-03-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_name', models.CharField(max_length=200)),
                ('retailer_id', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('years_in_market', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('crops', models.CharField(blank=True, max_length=200)),
                ('min_quality_grade', models.IntegerField(blank=True)),
                ('payment_modes', models.CharField(blank=True, max_length=200)),
                ('images', models.ImageField(blank=True, upload_to='photos/products')),
                ('max_loan_sanction', models.IntegerField(blank=True)),
                ('mortgage_required', models.BooleanField(blank=True)),
                ('loan_approval_successrate', models.IntegerField(blank=True)),
                ('rate_of_interest', models.FloatField(blank=True)),
                ('sanction_period', models.IntegerField(blank=True)),
            ],
        ),
    ]
