# Generated by Django 4.0.2 on 2022-03-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='loan_approval_successrate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='max_loan_sanction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='min_quality_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='rate_of_interest',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='sanction_period',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
