# Generated by Django 4.0.4 on 2022-04-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coordinates',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='land_amount',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='major_crop',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='soil_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='tenure_period',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size'), ('grade', 'grade')], max_length=100),
        ),
    ]
