# Generated by Django 4.0.4 on 2022-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_coordinates_product_land_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_crops',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='years_market',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('grade', 'grade'), ('size', 'size')], max_length=100),
        ),
    ]
