# Generated by Django 4.0.4 on 2022-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_deal_crops_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='equipment_rent',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
