# Generated by Django 4.0.4 on 2022-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_equipment_name_product_equipment_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size'), ('grade', 'grade')], max_length=100),
        ),
    ]
