# Generated by Django 4.0.4 on 2022-04-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('grade', 'grade'), ('size', 'size')], max_length=100),
        ),
    ]
